### ISSUE TITLE
after updating dapr to version 1.0.1, pubsub example does not work any more 

### ISSUE THREAD

**Issue by callalilychen** [dapr/python-sdk#204]
## Expected Behavior

https://github.com/dapr/python-sdk/tree/master/examples/pubsub-simple works without reporting any errors

## Actual Behavior

subscriber can not receive any messages:
```
> dapr run --app-id python-subscriber --app-protocol grpc --app-port 50051 --log-level debug  python3 subscriber.py
ℹ️  Starting Dapr with id python-subscriber. HTTP Port: 40589. gRPC Port: 46343
INFO[0000] starting Dapr Runtime -- version 1.0.1 -- commit 45bc40d  app_id=python-subscriber instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
INFO[0000] log level set to: debug                       app_id=python-subscriber instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
INFO[0000] metrics server started on :44781/             app_id=python-subscriber instance=ryzen5 scope=dapr.metrics type=log ver=1.0.1
INFO[0000] standalone mode configured                    app_id=python-subscriber instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
INFO[0000] app id: python-subscriber                     app_id=python-subscriber instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
INFO[0000] mTLS is disabled. Skipping certificate request and tls validation  app_id=python-subscriber instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
INFO[0000] local service entry announced: python-subscriber -> 192.168.0.183:43449  app_id=python-subscriber instance=ryzen5 scope=dapr.contrib type=log ver=1.0.1
INFO[0000] Initialized name resolution to standalone     app_id=python-subscriber instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
DEBU[0000] loading component. name: pubsub, type: pubsub.redis/  app_id=python-subscriber instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
INFO[0000] component loaded. name: pubsub, type: pubsub.redis/  app_id=python-subscriber instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
DEBU[0000] loading component. name: statestore, type: state.redis/  app_id=python-subscriber instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
INFO[0000] component loaded. name: statestore, type: state.redis/  app_id=python-subscriber instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
DEBU[0000] loading component. name: zipkin, type: exporters.zipkin/  app_id=python-subscriber instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
INFO[0000] waiting for all outstanding components to be processed  app_id=python-subscriber instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
FATA[0000] process component zipkin error: incorrect type exporters.zipkin  app_id=python-subscriber instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
⚠  Could not update sidecar metadata for cliPID: PUT http://127.0.0.1:40589/v1.0/metadata/cliPID giving up after 5 attempts
ℹ️  Updating metadata for app command: python3 subscriber.py
⚠  Could not update sidecar metadata for appCommand: PUT http://127.0.0.1:40589/v1.0/metadata/appCommand giving up after 5 attempt
```

publisher report errors:
```
> dapr run --app-id python-publisher --app-protocol grpc --dapr-grpc-port=3500 --log-level debug python3 publisher.py
ℹ️  Starting Dapr with id python-publisher. HTTP Port: 43039. gRPC Port: 3500
ℹ️  Checking if Dapr sidecar is listening on HTTP port 43039
INFO[0000] starting Dapr Runtime -- version 1.0.1 -- commit 45bc40d  app_id=python-publisher instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
INFO[0000] log level set to: debug                       app_id=python-publisher instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
INFO[0000] metrics server started on :38619/             app_id=python-publisher instance=ryzen5 scope=dapr.metrics type=log ver=1.0.1
INFO[0000] standalone mode configured                    app_id=python-publisher instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
INFO[0000] app id: python-publisher                      app_id=python-publisher instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
INFO[0000] mTLS is disabled. Skipping certificate request and tls validation  app_id=python-publisher instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
INFO[0000] local service entry announced: python-publisher -> 192.168.0.183:41515  app_id=python-publisher instance=ryzen5 scope=dapr.contrib type=log ver=1.0.1
INFO[0000] Initialized name resolution to standalone     app_id=python-publisher instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
DEBU[0000] loading component. name: pubsub, type: pubsub.redis/  app_id=python-publisher instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
INFO[0000] component loaded. name: pubsub, type: pubsub.redis/  app_id=python-publisher instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
DEBU[0000] loading component. name: statestore, type: state.redis/  app_id=python-publisher instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
INFO[0000] component loaded. name: statestore, type: state.redis/  app_id=python-publisher instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
DEBU[0000] loading component. name: zipkin, type: exporters.zipkin/  app_id=python-publisher instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
FATA[0000] process component zipkin error: incorrect type exporters.zipkin  app_id=python-publisher instance=ryzen5 scope=dapr.runtime type=log ver=1.0.1
⚠  Dapr sidecar is not listening on HTTP port: dial tcp 127.0.0.1:43039: connect: connection refused
ℹ️  Checking if Dapr sidecar is listening on GRPC port 3500
⚠  Dapr sidecar is not listening on GRPC port: dial tcp 127.0.0.1:3500: connect: connection refused
⚠  Dapr sidecar might not be responding.
== APP == Traceback (most recent call last):

== APP ==   File "/data/tools/dapr/python-sdk/examples/pubsub-simple/publisher.py", line 21, in <module>

== APP ==     resp = d.publish_event(

== APP == TypeError: publish_event() got an unexpected keyword argument 'topic_name'

⚠  Could not update sidecar metadata for cliPID: PUT http://127.0.0.1:43039/v1.0/metadata/cliPID giving up after 5 attempts
ℹ️  Updating metadata for app command: python3 publisher.py
⚠  Could not update sidecar metadata for appCommand: PUT http://127.0.0.1:43039/v1.0/metadata/appCommand giving up after 5 attempts
```

## Steps to Reproduce the Problem

After start dapr 1.0.1 with `dapr init`. Then follow the readme in the example folder.

**Comment by callalilychen** [comment]
state store example also does not work any more for me:

```
⚠  Dapr sidecar is not listening on HTTP port: dial tcp 127.0.0.1:44785: connect: connection refused
ℹ️  Checking if Dapr sidecar is listening on GRPC port 45685
⚠  Dapr sidecar is not listening on GRPC port: dial tcp 127.0.0.1:45685: connect: connection refused
⚠  Dapr sidecar might not be responding.
== APP == Traceback (most recent call last):

== APP ==   File "/data/tools/dapr/python-sdk/examples/state_store/state_store.py", line 27, in <module>

== APP ==     d.wait(5)

== APP ==   File "/data/tools/dapr/python-sdk/examples/pubsub-simple/.venv/lib/python3.9/site-packages/dapr/clients/grpc/client.py", line 810, in wait

== APP ==     raise e

== APP ==   File "/data/tools/dapr/python-sdk/examples/pubsub-simple/.venv/lib/python3.9/site-packages/dapr/clients/grpc/client.py", line 805, in wait

== APP ==     s.connect(host_port)

== APP == ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by Ilozuluchris** [comment]
@callalilychen Not a fix: but for the pubsub example downgrade your runtime version to version 1 and upgrade the python libraries via pip if you have not. That worked for me.

**Comment by wenwenchenbosch** [comment]
@Ilozuluchris how to downgrading dapr runtime? I downgraded dapr cli, and try `dapr init`. The newest dapr runtime is then installed.

**Comment by Ilozuluchris** [comment]
@callalilychen  Use `dapr init --runtime-version runtime_version_number`, where `runtime_version_number` is the version number you want to use, you might need to uninstall the current runtime first with `dapr uninstall`. You can find runtime versions [here](https://github.com/dapr/dapr/releases)

**Comment by wcs1only** [comment]
Which version of the python-sdk are you currently using? Using dapr runtime v1.0.1 requires python-sdk >= 1.0.0:
```bash
pip show dapr
Name: dapr
Version: 1.0.0
Summary: The official release of Dapr Python SDK.
Home-page: https://dapr.io/
Author: Dapr Authors
Author-email: daprweb@microsoft.com
License: MIT
Location: /usr/local/lib/python3.9/site-packages
Requires: protobuf, python-dateutil, grpcio, aiohttp
Required-by: dapr-ext-grpc, dapr-ext-fastapi
```

**Comment by wenwenchenbosch** [comment]
After I downgraded my dapr runtime to 1.0.0, I still facing the same problem.
And checked dapr python sdk and also `dapr-ext-grpc` version. It shows also v1.0.0:
```
pip show dapr
Name: dapr
Version: 1.0.0
Summary: The official release of Dapr Python SDK.
Home-page: https://dapr.io/
Author: Dapr Authors
Author-email: daprweb@microsoft.com
License: MIT
Location: /data/tools/kuksa.val/kuksa_apps/dapr/pubsub/.venv/lib/python3.9/site-packages
Requires: protobuf, aiohttp, python-dateutil, grpcio
Required-by: dapr-ext-grpc
```

I tried the whole thing with my laptop, which installed the same OS like my pc. On my laptop, everything works fine. But on my pc, It worked with runtime 0.8.0, not any more with version >= 1.0.0. Maybe there is issues with ryzen CPU? On my PC, ryzen5 is installed. And I also see ryzen5 in the error message.

**Comment by wcs1only** [comment]
That's just your machine's hostname, I believe. We don't have any processor specific code, so I would be shocked. I missed this on the first pass read of your error message, but it looks like you might be hitting a known issue when upgrading from an older version of the runtime:

https://github.com/dapr/dapr/issues/2960#issuecomment-804628039

If you do a ```dapr uninstall --all && dapr init``` That should remove the zipkin component file that's causing the issue.

**Comment by wenwenchenbosch** [comment]
tested and it works, thanks very much :+1:
