### ISSUE TITLE
Demo Actor: Failed to run

### ISSUE THREAD

**Issue by anhldbk** [dapr/python-sdk#252]
## Overview

I failed to run the demo in [self-hosted mode](https://github.com/dapr/python-sdk/blob/master/examples/demo_actor/README.md#run-in-self-hosted-mode)

## Details

In step 2, while invoking

```sh
# Run actor client
cd demo_actor
dapr run --app-id demo-client python3 demo_actor_client.py
```

I got an error of

```sh
== APP == Traceback (most recent call last):
== APP ==   File "/Users/anhld/Works/code/dapr/actor/demo_actor_client.py", line 63, in <module>
== APP ==     asyncio.run(main())
== APP ==   File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
== APP ==     return loop.run_until_complete(main)
== APP ==   File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
== APP ==     return future.result()
== APP ==   File "/Users/anhld/Works/code/dapr/actor/demo_actor_client.py", line 20, in main
== APP ==     rtn_bytes = await proxy.invoke_method("GetMyData")
== APP ==   File "/usr/local/lib/python3.9/site-packages/dapr/actor/client/proxy.py", line 154, in invoke_method
== APP ==     return await self._dapr_client.invoke_method(
== APP ==   File "/usr/local/lib/python3.9/site-packages/dapr/clients/http/dapr_actor_http_client.py", line 50, in invoke_method
== APP ==     body, r = await self._client.send_bytes(method='POST', url=url, data=data)
== APP ==   File "/usr/local/lib/python3.9/site-packages/dapr/clients/http/client.py", line 76, in send_bytes
== APP ==     raise (await self.convert_to_error(r))
== APP == dapr.clients.exceptions.DaprInternalError: ('actor runtime is not configured', 'ERR_ACTOR_RUNTIME_NOT_FOUND')
```

## Analysis

From the error log, the client seems to NOT fully initialize the runtime. 

## Suggestion

Add another flask-based demo & modify the doc

```python
from flask import Flask

from dapr.clients import DaprClient
from dapr.actor import ActorProxy, ActorId
from demo_actor_interface import DemoActorInterface

from dapr.conf import settings
app = Flask('cart')


@app.route('/add', methods=['POST'])
async def add():
    proxy = ActorProxy.create('DemoActor', ActorId('1'), DemoActorInterface)

    # -----------------------------------------------
    # Actor invocation demo
    # -----------------------------------------------
    # non-remoting actor invocation
    print("call actor method via proxy.invoke_method()", flush=True)
    rtn_bytes = await proxy.invoke_method("GetMyData")
    return rtn_bytes.decode('UTF-8'), 200


# Run application
if __name__ == '__main__':
    print("> Gonna listen on port=%s" % settings.APP_PORT)
    print(settings)
    app.run(port=settings.APP_PORT)
```

## Note

I already discussed this issue [on Discord](https://discord.com/channels/778680217417809931/782286950983663617/868711495142367253)

**Comment by anhldbk** [comment]
@wcs1only Should I make a PR?

**Comment by wcs1only** [comment]
You can, but our automated validation for this example is currently passing:
https://github.com/dapr/python-sdk/runs/3221025579?check_suite_focus=true#step:16:937

Runtime not initialized generally means we're missing a dependent component. Can you post the daprd logs associated with the failing run? That might shed some light on the failure.

**Comment by wcs1only** [comment]
@anhldbk Since we haven't had any activity on this issue in several months, I'm going to close this issue. If you are still having trouble, please open a new issue with daprd logs included.

**Comment by lizzzcai** [comment]
hi @wcs1only ,
I am following the demo to run the actor but also failed, below is the error

```
❯ dapr run --app-id demo-client python3 demo_actor_client.py
ℹ️  Starting Dapr with id demo-client. HTTP Port: 64515. gRPC Port: 64516
ℹ️  Checking if Dapr sidecar is listening on HTTP port 64515
INFO[0000] starting Dapr Runtime -- version 1.5.1 -- commit c6daae8e9b11b3e241a9cb84c33e5aa740d74368  app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
INFO[0000] log level set to: info                        app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
INFO[0000] metrics server started on :64517/             app_id=demo-client instance=C02F51RLMD6R scope=dapr.metrics type=log ver=1.5.1
INFO[0000] standalone mode configured                    app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
INFO[0000] app id: demo-client                           app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
INFO[0000] mTLS is disabled. Skipping certificate request and tls validation  app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
INFO[0000] local service entry announced: demo-client -> 10.128.33.117:64523  app_id=demo-client instance=C02F51RLMD6R scope=dapr.contrib type=log ver=1.5.1
INFO[0000] Initialized name resolution to mdns           app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
INFO[0000] loading components                            app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
INFO[0000] component loaded. name: pubsub, type: pubsub.redis/v1  app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
INFO[0000] waiting for all outstanding components to be processed  app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
INFO[0000] component loaded. name: statestore, type: state.redis/v1  app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
INFO[0000] all outstanding components processed          app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
INFO[0000] enabled gRPC tracing middleware               app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime.grpc.api type=log ver=1.5.1
INFO[0000] enabled gRPC metrics middleware               app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime.grpc.api type=log ver=1.5.1
INFO[0000] API gRPC server is running on port 64516      app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
INFO[0000] enabled metrics http middleware               app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime.http type=log ver=1.5.1
INFO[0000] enabled tracing http middleware               app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime.http type=log ver=1.5.1
INFO[0000] http server is running on port 64515          app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
INFO[0000] The request body size parameter is: 4         app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
INFO[0000] enabled gRPC tracing middleware               app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime.grpc.internal type=log ver=1.5.1
INFO[0000] enabled gRPC metrics middleware               app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime.grpc.internal type=log ver=1.5.1
INFO[0000] internal gRPC server is running on port 64523  app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
INFO[0000] actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s  app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime.actor type=log ver=1.5.1
WARN[0000] app channel not initialized, make sure -app-port is specified if pubsub subscription is required  app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
WARN[0000] failed to read from bindings: app channel not initialized   app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
INFO[0000] dapr initialized. Status: Running. Init Elapsed 11.476999999999999ms  app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime type=log ver=1.5.1
ℹ️  Checking if Dapr sidecar is listening on GRPC port 64516
ℹ️  Dapr sidecar is up and running.
ℹ️  Updating metadata for app command: python3 demo_actor_client.py
✅  You're up and running! Both Dapr and your app logs will appear here.

INFO[0000] placement tables updated, version: 31         app_id=demo-client instance=C02F51RLMD6R scope=dapr.runtime.actor.internal.placement type=log ver=1.5.1
== APP == call actor method via proxy.invoke_method()
== APP == Traceback (most recent call last):
== APP ==   File "/Users/i543026/dev/demo/dapr-demo/actor-python/demo_actor/demo_actor_client.py", line 71, in <module>
== APP ==     asyncio.run(main())
== APP ==   File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
== APP ==     return loop.run_until_complete(main)
== APP ==   File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
== APP ==     return future.result()
== APP ==   File "/Users/i543026/dev/demo/dapr-demo/actor-python/demo_actor/demo_actor_client.py", line 28, in main
== APP ==     rtn_bytes = await proxy.invoke_method("GetMyData")
== APP ==   File "/Users/i543026/dev/demo/dapr-demo/env/lib/python3.9/site-packages/dapr/actor/client/proxy.py", line 154, in invoke_method
== APP ==     return await self._dapr_client.invoke_method(
== APP ==   File "/Users/i543026/dev/demo/dapr-demo/env/lib/python3.9/site-packages/dapr/clients/http/dapr_actor_http_client.py", line 58, in invoke_method
== APP ==     body, _ = await self._client.send_bytes(method='POST', url=url, data=data, headers=headers)
== APP ==   File "/Users/i543026/dev/demo/dapr-demo/env/lib/python3.9/site-packages/dapr/clients/http/client.py", line 65, in send_bytes
== APP ==     r = await session.request(
== APP ==   File "/Users/i543026/dev/demo/dapr-demo/env/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
== APP ==     await resp.start(conn)
== APP ==   File "/Users/i543026/dev/demo/dapr-demo/env/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 913, in start
== APP ==     self._continue = None
== APP ==   File "/Users/i543026/dev/demo/dapr-demo/env/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
== APP ==     raise asyncio.TimeoutError from None
== APP == asyncio.exceptions.TimeoutError
❌  The App process exited with error code: exit status 1
ℹ️  
terminated signal received: shutting down
✅  Exited Dapr successfully
```
