### ISSUE TITLE
Postgresql return error when I using as output binding.

### ISSUE THREAD

**Issue by tarrantro** [dapr/python-sdk#353]
## Ask your question here
I found in the official document about how to use sdk to call output binding and try to integrate with my postgresql. However, it returns error even I tried to put test data into the invoke function. Error as below. 

===
Error:
```
INFO:root:Data: {"operation": "exec", "metadata": {"sql": "INSERT INTO orders_archive (id, item, start_timestamp, end_timestamp) VALUES ('001', 'computer', '2022-02-03 14:22:17.394219', '2022-02-03 14:22:17.394382')"}}
Traceback (most recent call last):
  File "//psql.py", line 34, in <module>
    archive_order(test_data)
  File "//psql.py", line 25, in archive_order
    return _operation("INSERT INTO orders_archive (id, item, start_timestamp, end_timestamp) VALUES ('{}', '{}', '{}', '{}')".format(data["id"],data["item"],data["start_timestamp"],str(datetime.datetime.utcnow())), 'exec')
  File "//psql.py", line 15, in _operation
    resp = client.invoke_binding(DAPR_ORDER_BINDING_NAME, operation, json.dumps(data))
  File "/usr/local/lib/python3.9/site-packages/dapr/clients/grpc/client.py", line 288, in invoke_binding
    response, call = self._stub.InvokeBinding.with_call(req, metadata=metadata)
  File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 957, in with_call
    return _end_unary_response_blocking(state, call, True, None)
  File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "error when invoke output binding szpcapoc001-psql-binding: metadata required"
	debug_error_string = "{"created":"@1643898137.400898725","description":"Error received from peer ipv4:127.0.0.1:50001","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"error when invoke output binding psql-binding: metadata required","grpc_status":13}"
```

=======
My code:
```python
import logging, os, datetime, json
from dapr.clients import DaprClient

logging.basicConfig(level = logging.INFO)

DAPR_ORDER_BINDING_NAME = os.environ['DAPR_ORDER_BINDING_NAME'] if os.environ.get('DAPR_ORDER_BINDING_NAME') else 'psql-binding'

def _operation(sql,operation='query'):
    data = {}
    data['operation'] = operation
    data['metadata'] = {"sql": sql}
    logging.info('Data: {}'.format(json.dumps(data)))

    with DaprClient() as client:
        resp = client.invoke_binding(DAPR_ORDER_BINDING_NAME, operation, json.dumps(data))

def archive_order(data):
    logging.info(f'Data: id: {data["id"]}, item "{data["item"]}"')

    return _operation("INSERT INTO orders_archive (id, item, start_timestamp, end_timestamp) VALUES ('{}', '{}', '{}', '{}')".format(data["id"],data["item"],data["start_timestamp"],str(datetime.datetime.utcnow())), 'exec')

if __name__ == '__main__':
    os.environ['DAPR_ORDER_BINDING_NAME'] = 'psql-binding'
    test_data = {
        "id": "001",
        "item": "computer",
        "start_timestamp": str(datetime.datetime.utcnow())
    }
    archive_order(test_data)


```

**Comment by berndverst** [comment]
Are you sure the Postgres component was initialized correctly? Doublecheck the connection string and look at the sidecar logs to ensure the component was initialized successfully.

Chances are the documentation for the Postgres Binding wrong, can you try changing `json.dumps(data)` to `json.dumps(data[metadata])` please?

That will probably do the trick.

**Comment by berndverst** [comment]
Please note that the `metadata` attribute refers to generic gRPC metadata and must not be used. Instead only use `binding_metadata`.

If you have any problem with the component after sending the required values (per the documentation) as metadata (via `binding_metadata`) please open an issue in the component-contrib repo.
