### ISSUE TITLE
ModuleNotFoundError: No module named 'dapr.version' (dapr-python 1.8.0)

### ISSUE THREAD

**Issue by youngbupark** [dapr/python-sdk#478]
## Expected Behavior

No error!

## Actual Behavior

```bash
youngp@DESKTOP_frlucas state_store % python3 state_store.py
Traceback (most recent call last):
  File "/Users/youngp/repos/samples/python-sdk/examples/state_store/state_store.py", line 8, in <module>
    from dapr.clients import DaprClient
  File "/usr/local/lib/python3.10/site-packages/dapr/clients/__init__.py", line 20, in <module>
    from dapr.clients.grpc.client import DaprGrpcClient, MetadataTuple, InvokeMethodResponse
  File "/usr/local/lib/python3.10/site-packages/dapr/clients/grpc/client.py", line 40, in <module>
    from dapr.version import __version__
ModuleNotFoundError: No module named 'dapr.version'
```

## Steps to Reproduce the Problem

1. Install the latest dapr pkg (1.8.0
2. Run state_store.py sample

## Release Note

RELEASE NOTE:

**Comment by espenairmine** [comment]
This breaks our code when upgrading to 1.8.0

**Comment by DarqueWarrior** [comment]
I saw the same thing last night. I had to pin my version to 1.6.0 to get back up and running.

**Comment by berndverst** [comment]
Thanks not sure why this happened but will fix!

**Comment by berndverst** [comment]
> I saw the same thing last night. I had to pin my version to 1.6.0 to get back up and running.

Why not pin the latest 1.7.X?

**Comment by youngbupark** [comment]
> > I saw the same thing last night. I had to pin my version to 1.6.0 to get back up and running.
> 
> Why not pin the latest 1.7.X? @DarqueWarrior

1.7.x works too. I pinned 1.7.0 for my app.

**Comment by berndverst** [comment]
I have yanked version 1.8.0 and will release 1.8.1 momentarily.

**Comment by berndverst** [comment]
Released 1.8.1 with the fix to ensure everyone pulls in the correct version. 1.8.0 is yanked and can no longer be installed.

Fix is here: https://github.com/dapr/python-sdk/commit/8f64c3ea259a1dd713308706e4a46f7b27b3e97b

**Comment by berndverst** [comment]
Please note that the Metadata API and Configuration API depend in `>=1.8.0` depend on proto changes that are only in Dapr Runtime 1.9.0. So you cannot use those Alpha APIs unless you upgrade to the new runtime release as well.

**Comment by berndverst** [comment]
@espenairmine @ngiind @DarqueWarrior @youngbupark fixed now. Sorry about that!

**Comment by DarqueWarrior** [comment]
I was in a hurry building my demo for Ignite so I pinned to the last known working version is all.
