### ISSUE TITLE
The SDK dependency on typing_extensions is not defined in setup.cfg

### ISSUE THREAD

**Issue by tmacam** [dapr/python-sdk#544]
With #521 the SDK gained an implicit dependency on `typing_extensions `. This dependency is mentioned on `dev-requirements.txt` but it is not re-stated in `setup.cfg`, meaning that it is not mentioned in the generated SDK Python package/egg, leaving new installs with a broken `DaprClient`.

## Expected Behavior

```python
>>> from dapr.clients import DaprClient
>>>
```

## Actual Behavior

```python
>>> from dapr.clients import DaprClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tmacam/.virtualenvs/pubsub-dapr-python-servicebus/lib/python3.8/site-packages/dapr/clients/__init__.py", line 20, in <module>
    from dapr.clients.grpc.client import DaprGrpcClient, MetadataTuple, InvokeMethodResponse
  File "/home/tmacam/.virtualenvs/pubsub-dapr-python-servicebus/lib/python3.8/site-packages/dapr/clients/grpc/client.py", line 24, in <module>
    from typing_extensions import Self
ModuleNotFoundError: No module named 'typing_extensions'
>>>
```

## Steps to Reproduce the Problem

1. On a new install, `pip install dapr`
2. On a Python REPL, run ` from dapr.clients import DaprClient`.
3. Boom!

## Release Note

RELEASE NOTE: **FIX** Define SDK's explicit dependency on typing_extensions

**Comment by tmacam** [comment]
Duplicate of #538
