### ISSUE TITLE
Actor JSON Serializer randomly failing

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/python-sdk#83]
## Expected Behavior

Correct serialization (99.9% of the time) on the HTTP endpoints for actors

## Actual Behavior

When running a Proxy call for the Actor implementation, it randomly fails and spits out a weird JSON string, as if something happened on the protocol transport. Below you can find 2 different occurrences:

**Occurrence #1:**

```bash
# /home/xanrin/dapr-python-sdk/dapr/actor/client/proxy.py (line 71)
b'[[0.056063172301151286,0.43107083116247324,-0.21845425248263262,-1.2186224010316111],1.0,true,{}]lse,{}]'

# /home/xanrin/dapr-python-sdk/dapr/serializers/json.py (line 49)
b'[[0.056063172301151286,0.43107083116247324,-0.21845425248263262,-1.2186224010316111],1.0,true,{}]lse,{}]'

# What I expect:
b'[[0.056063172301151286,0.43107083116247324,-0.21845425248263262,-1.2186224010316111],1.0,true,{}]'
```

**Occurrence #2:**

```bash
# /home/xanrin/dapr-python-sdk/dapr/actor/client/proxy.py (line 71)
b'[[0.02180521361883352,0.9327880131478761,-0.04958054991416051,-1.4610110113961423],1.0,false,{}]]'

# /home/xanrin/dapr-python-sdk/dapr/serializers/json.py (line 49)
b'[[0.02180521361883352,0.9327880131478761,-0.04958054991416051,-1.4610110113961423],1.0,false,{}]]'

# What I expect (there is a ] too much):
b'[[0.02180521361883352,0.9327880131478761,-0.04958054991416051,-1.4610110113961423],1.0,false,{}]'
```

## Stacktrace

```bash
== APP == Process ForkServerProcess-4:
== APP == Traceback (most recent call last):
== APP ==   File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
== APP ==     self.run()
== APP ==   File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
== APP ==     self._target(*self._args, **self._kwargs)
== APP ==   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/common/vec_env/subproc_vec_env.py", line 18, in _worker
== APP ==     observation, reward, done, info = env.step(data)
== APP ==   File "/mnt/e/Projects/roadwork-rl/src/Lib/python/roadwork/roadwork/client/client_dapr.py", line 91, in step
== APP ==     obs, reward, done, info = asyncio.get_event_loop().run_until_complete(self.proxy.SimStep({ 'action': action }))
== APP ==   File "/usr/local/lib/python3.7/dist-packages/nest_asyncio.py", line 59, in run_until_complete
== APP ==     return f.result()
== APP ==   File "/usr/lib/python3.7/asyncio/futures.py", line 181, in result
== APP ==     raise self._exception
== APP ==   File "/usr/lib/python3.7/asyncio/tasks.py", line 249, in __step
== APP ==     result = coro.send(None)
== APP ==   File "/home/xanrin/dapr-python-sdk/dapr/actor/client/proxy.py", line 71, in __call__
== APP ==     return self._message_serializer.deserialize(rtnval, self._attr_call_type['return_types'])
== APP == Actor sending: b'[[0.056063172301151286,0.43107083116247324,-0.21845425248263262,-1.2186224010316111],1.0,true,{}]lse,{}]'
== APP == Decoding: b'[[0.056063172301151286,0.43107083116247324,-0.21845425248263262,-1.2186224010316111],1.0,true,{}]lse,{}]'
== APP ==   File "/home/xanrin/dapr-python-sdk/dapr/serializers/json.py", line 49, in deserialize
== APP == Actor sending: b'[[0.056063172301151286,0.43107083116247324,-0.21845425248263262,-1.2186224010316111],1.0,true,{}]lse,{}]'
== APP == Decoding: b'[[0.056063172301151286,0.43107083116247324,-0.21845425248263262,-1.2186224010316111],1.0,true,{}]lse,{}]'
== APP ==     obj = json.loads(data, cls=DaprJSONDecoder)
== APP ==   File "/usr/lib/python3.7/json/__init__.py", line 361, in loads
== APP ==     return cls(**kw).decode(s)
== APP ==   File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
== APP ==     raise JSONDecodeError("Extra data", s, end)
== APP == json.decoder.JSONDecodeError: Extra data: line 1 column 96 (char 95)
```

## Steps to Reproduce the Problem

This happens when running an application that is utilizing a ThreadPool and running > 1000 reqs / sec (estimated)

**Comment by XavierGeerinck** [comment]
Adding @youngbupark since I think it's you that wrote the Actor implementation and could maybe help here? :)

**Comment by XavierGeerinck** [comment]
Update: I am thinking it's due to aiohttp (https://github.com/aio-libs/aiohttp/issues/3881)

**Comment by youngbupark** [comment]
> Update: I am thinking it's due to aiohttp ([aio-libs/aiohttp#3881](https://github.com/aio-libs/aiohttp/issues/3881))

Yeah looks like it.

**Comment by XavierGeerinck** [comment]
> > Update: I am thinking it's due to aiohttp ([aio-libs/aiohttp#3881](https://github.com/aio-libs/aiohttp/issues/3881))
> 
> Yeah looks like it.

What do you suggest here? Seeing that it's in the Dapr code :-)

**Comment by youngbupark** [comment]
> > > Update: I am thinking it's due to aiohttp ([aio-libs/aiohttp#3881](https://github.com/aio-libs/aiohttp/issues/3881))
> > 
> > 
> > Yeah looks like it.
> 
> What do you suggest here? Seeing that it's in the Dapr code :-)

We will look at it :) I put P1 label on this.

**Comment by XavierGeerinck** [comment]
> > > > Update: I am thinking it's due to aiohttp ([aio-libs/aiohttp#3881](https://github.com/aio-libs/aiohttp/issues/3881))
> > > 
> > > 
> > > Yeah looks like it.
> > 
> > 
> > What do you suggest here? Seeing that it's in the Dapr code :-)
> 
> We will look at it :) I put P1 label on this.

You rock! 😀

**Comment by XavierGeerinck** [comment]
Any update on this? :)

**Comment by youngbupark** [comment]
@amanbha @msfussell @orizohar I will prioritize this bug as P0 because it is blocking one of python-users.

**Comment by youngbupark** [comment]
@XavierGeerinck I tried to reproduce this issue using demo_actor app, but I could not.

According to the log that you attached, I do not think it is related to aiohttp bug because the response seems to overlap the previously received data rather than truncate the data. ActorProxy is asynchronous calls, but seems like you make this async call to sync call in multiple threads. It might be the root cause of this problem. 

Can you please share your code?

**Comment by XavierGeerinck** [comment]
Thanks a lot for diving into this @youngbupark , what you say might make sense actually... sadly enough I am struggling with the issue that the calls have to be synchronous due to the Libraries I am utilizing.

The entire code base I am working on can be found here: https://github.com/Roadwork/Roadwork-RL/tree/master/src (including diagrams). When you speak about "overlapping" data instead of truncating (I've never thought of it in this way, thanks a lot for this hint!) the first thing coming to my mind is the "Nest Asyncio" library (https://pypi.org/project/nest-asyncio/) that I am utilizing to access the event loop.

I wonder if I am able to create the event loop per thread 🤔 that might indeed solve the overlapping issue then. 

What do you think? Is this the way I should be thinking about it? (again: sync is a requirement due to the third party libraries). Definitely open towards going through the problem together, but if it's overlapping I definitely understand that it's not a Dapr issue (nor asyncio one).

**Comment by youngbupark** [comment]
@XavierGeerinck let's not use nest-asyncio. Instead, try to use [asyncio.run()](https://docs.python.org/3/library/asyncio-task.html#asyncio.run) or [django's async_to_sync](https://stackoverflow.com/questions/59503825/django-async-to-sync-vs-asyncio-run) to make async call to sync. 

Also try to scale out the replicaset of actor services. Please update the status then I can follow it up tomorrow morning.

**Comment by XavierGeerinck** [comment]
Thanks for the quick comment! I switched it all out towards asgiref's `async_to_sync` and creating async methods where they should be (reference: https://github.com/Roadwork/Roadwork-RL/commit/b62e5723d6618b0bd92f80f8a4d16a82d8dfe38e) but the problem still exists.

Latest stacktrace (I marked the strange line):

```diff
== APP == Process ForkServerProcess-7:
== APP == Traceback (most recent call last):
== APP ==   File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
== APP ==     self.run()
== APP ==   File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
== APP ==     self._target(*self._args, **self._kwargs)
== APP ==   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/common/vec_env/subproc_vec_env.py", line 18, in _worker
== APP ==     observation, reward, done, info = env.step(data)
== APP ==   File "/mnt/e/Projects/roadwork-rl/src/Lib/python/roadwork/roadwork/client/client_dapr.py", line 124, in step
== APP ==     obs, reward, done, info = self._step(action)
== APP ==   File "/usr/local/lib/python3.7/dist-packages/asgiref/sync.py", line 139, in __call__
== APP ==     return call_result.result()
== APP ==   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
== APP ==     return self.__get_result()
== APP ==   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
== APP ==     raise self._exception
== APP ==   File "/usr/local/lib/python3.7/dist-packages/asgiref/sync.py", line 204, in main_wrap
== APP ==     result = await self.awaitable(*args, **kwargs)
== APP ==   File "/mnt/e/Projects/roadwork-rl/src/Lib/python/roadwork/roadwork/client/client_dapr.py", line 60, in _step
== APP ==     obs, reward, done, info = await self.proxy.SimStep({ 'action': action })
== APP ==   File "/home/xanrin/dapr-python-sdk/dapr/actor/client/proxy.py", line 70, in __call__
== APP ==     return self._message_serializer.deserialize(rtnval, self._attr_call_type['return_types'])
== APP ==   File "/home/xanrin/dapr-python-sdk/dapr/serializers/json.py", line 49, in deserialize
== APP ==     obj = json.loads(data, cls=DaprJSONDecoder)
== APP ==   File "/usr/lib/python3.7/json/__init__.py", line 361, in loads
== APP ==     return cls(**kw).decode(s)
== APP ==   File "/usr/lib/python3.7/json/decoder.py", line 341, in decode
== APP ==     raise JSONDecodeError("Extra data", s, end)
- == APP == json.decoder.JSONDecodeError: Extra data: line 1 column 98 (char 97)
== APP == Traceback (most recent call last):
== APP ==   File "./Experiments/baselines/cartpole/train.py", line 27, in <module>
== APP ==     model.learn(total_timesteps=100000)
== APP ==   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/ppo2/ppo2.py", line 336, in learn
== APP ==     rollout = self.runner.run(callback)
== APP ==   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/common/runners.py", line 48, in run
== APP ==     return self._run()
== APP ==   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/ppo2/ppo2.py", line 482, in _run
== APP ==     self.obs[:], rewards, self.dones, infos = self.env.step(clipped_actions)
== APP ==   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/common/vec_env/base_vec_env.py", line 150, in step
== APP ==     return self.step_wait()
== APP ==   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/common/vec_env/subproc_vec_env.py", line 107, in step_wait
== APP ==     results = [remote.recv() for remote in self.remotes]
== APP ==   File "/usr/local/lib/python3.7/dist-packages/stable_baselines/common/vec_env/subproc_vec_env.py", line 107, in <listcomp>
== APP ==     results = [remote.recv() for remote in self.remotes]
== APP ==   File "/usr/lib/python3.7/multiprocessing/connection.py", line 250, in recv
== APP ==     buf = self._recv_bytes()
== APP ==   File "/usr/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
== APP ==     buf = self._recv(4)
== APP ==   File "/usr/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
== APP ==     raise EOFError
== APP == EOFError
```

**Comment by youngbupark** [comment]
@XavierGeerinck please do not create new event loop in (reference: Roadwork/Roadwork-RL@b62e572). Try to test it again.

Also please let me know how I can reproduce on my environment. Did you test it on local machine or on K8s ?

**Comment by XavierGeerinck** [comment]
I forgot to push the latest changes :) I had indeed removed that new event loop creation already.

I tested on a local machine environment, but you should be able to reproduce it with the container installation part (https://github.com/Roadwork/Roadwork-RL/tree/master/src under "Kubernetes")

**Comment by youngbupark** [comment]
@XavierGeerinck I can reproduce it now. I am investigating this.

**Comment by youngbupark** [comment]
I captured tcp traffic of server and client side with wireshark
> You can open the captured packets on wireshark by downloading this [high_freq.pcapng.gz](https://github.com/dapr/python-sdk/files/4963842/high_freq.pcapng.gz)

Based on the investigation, actorservice returns correct json format response when proxy calls actor and its method. but when dapr sidecar send the response from actor service to client via http client. the data is corrupted. 

For example, two invocation requests, such as A and B, come to dapr sidecar for invocation in a row with almost several ns time gap, where A comes first and B next. actorservice returns the response for B and then response for A. but B's response body was same as A's response body, but no header change. B's headers were not changed and content-length is correct for B's original body. 

so when proxy tried to deserialize B's response body, it was failed because B's response body was A's and B's data was truncated or B's data included garbage data. 

We will investigate this issue more and fix runtime as soon as possible.

**Comment by youngbupark** [comment]
cc/ @yaron2 @amanbha @LMWF @yolember

**Comment by youngbupark** [comment]
@XavierGeerinck I found the root cause of this issue and will fix the bug and release 0.9.1 tomorrow.

**Comment by XavierGeerinck** [comment]
Awesome! Amazing work, you rock! Looking forward to see what was causing this 😊
